### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by dubhcait** [fac-graduate-programme/Nova-Foundation#17]
- Function component
  - props: `{isLogged}`<br>
  
  `isLogged` is needed to determine what navlinks would appear on the menu component. <br>
  Here is an idea of what could be done here:
  ```javascript
  //if logged in
  const navLinksForUsers = [
    {text: 'Nova Home', path: '/home'},
    {text: 'Nova Information', path: '/information'},
    {text: 'Nova Stories', path: '/stories'},
    {text: 'Personal Space', path: '/personal-space'},
    {text: 'Logout', path: '/logout'},
  ]
  //if not logged in
  const navLinksForVisitors = [
    {text: 'Nova Home', path: '/'},
    {text: 'About US', path: '/about-us'},
  ]
  ```
   - Map through one of these arrays to create a list of items(`li` or `button`)
   - `redirectOnClick(path)`:
   When the user clicks on one of these buttons/items, it redirects him to the required page. This could be done using `Redirect` component from `react-dom-router` but I prefer `props.history.push(path)` to maintain our router history. Either way is okay after all!
   - All props are required

**Comment by Dalmano** [comment]
![Screenshot from 2019-08-05 16-46-57](https://user-images.githubusercontent.com/30301023/62477427-dbb17000-b7a0-11e9-9584-867c61916ee4.png)

**Comment by dubhcait** [comment]
![](https://i.imgur.com/qdWmy84.png)

background: #C4D5ED;

border: 1px solid #6690D0;
border-radius: 5px;

font-family: Lato;
font-style: normal;
font-weight: normal;
font-size: 12px;
line-height: 14px;
display: flex;
align-items: center;

color: #000000;

**hover** 
background: #B1C7E7;
font-weight: bold;

![](https://i.imgur.com/sLXKfts.png)


![](https://i.imgur.com/ivIqEYp.png)

background: #FAF8F8;
border: 1px solid #6690D0;

font-family: Roboto;
font-style: normal;
font-weight: normal;
font-size: 13px;
line-height: 15px;
display: flex;
align-items: center;
text-align: center;

color: #000000;
