### ISSUE TITLE
Button

### ISSUE THREAD

**Issue by dubhcait** [fac-graduate-programme/Nova-Foundation#18]
- Function component
  - props: `{className, action, text`<br>
  
  className is needed because we have different styles for buttons.
```js
  <Button className='login__button' action={this.submitForm} text='Login'/>
```
  - All props are required

**Comment by Dalmano** [comment]
![Screenshot from 2019-08-05 16-52-40](https://user-images.githubusercontent.com/30301023/62477756-86c22980-b7a1-11e9-94fc-0ac61c76a31b.png)

/* Rectangle */


position: absolute;
left: 0%;
right: 0%;
top: 0%;
bottom: 0%;

/* Primary buttons */

background: linear-gradient(90deg, #F27088 -4%, #C33650 96.67%);
border-radius: 20px;

**Comment by Dalmano** [comment]
![Screenshot from 2019-08-05 16-54-27](https://user-images.githubusercontent.com/30301023/62477877-c721a780-b7a1-11e9-94aa-14996f87ba46.png)

/* Rectangle 3 */


position: absolute;
width: 100px;
height: 35px;
left: 110px;
top: 463px;

/* Primary buttons */

background: linear-gradient(90deg, #F27088 -4%, #C33650 96.67%);
border-radius: 5px;

**Comment by Dalmano** [comment]
![Screenshot from 2019-08-05 16-56-13](https://user-images.githubusercontent.com/30301023/62478019-09e37f80-b7a2-11e9-9d70-5ef07de72e35.png)

/* Rectangle */


position: absolute;
height: 45px;
left: 0%;
right: 0%;
top: 0px;

/* Grey */

background: #A0A3A6;
border-radius: 20px;

/* Rectangle */


position: absolute;
height: 45px;
left: 0%;
right: 0%;
top: 0px;

/* Primary buttons */

background: linear-gradient(90deg, #F27088 -4%, #C33650 96.67%);
border-radius: 20px;

**Comment by Dalmano** [comment]
![Screenshot from 2019-08-05 17-02-39](https://user-images.githubusercontent.com/30301023/62478439-01d80f80-b7a3-11e9-9119-3940373cd6ab.png)

/* Rectangle 3 */


position: absolute;
width: 200px;
height: 36px;
left: 60px;
top: 585px;

/* Primary buttons */

background: linear-gradient(90deg, #F27088 -4%, #C33650 96.67%);
border-radius: 5px;

/* Rectangle 3.1 */


position: absolute;
width: 200px;
height: 37px;
left: 60px;
top: 647px;

background: rgba(196, 196, 196, 0.35);
border-radius: 5px;

**Comment by Dalmano** [comment]
![Screenshot from 2019-08-05 17-06-36](https://user-images.githubusercontent.com/30301023/62478659-80cd4800-b7a3-11e9-91f9-aa75ef9e5b73.png)

/* Rectangle */


position: absolute;
left: 13.44%;
right: 52.19%;
top: 34.87%;
bottom: 56.35%;

/* Primary buttons */

background: linear-gradient(90deg, #F27088 -4%, #C33650 96.67%);
border-radius: 20px;

**Comment by Dalmano** [comment]
![Screenshot from 2019-08-05 17-11-40](https://user-images.githubusercontent.com/30301023/62478950-4b752a00-b7a4-11e9-843c-3dad947c015e.png)

/* Rectangle 3.1 */


position: absolute;
width: 65px;
height: 35.23px;
left: 136px;
top: 447.54px;

background: rgba(196, 196, 196, 0.35);
border-radius: 5px;

/* Rectangle 3 */


position: absolute;
width: 65px;
height: 35.23px;
left: 214px;
top: 446.54px;

/* Primary buttons */

background: linear-gradient(90deg, #F27088 -4%, #C33650 96.67%);
border-radius: 5px;

**Comment by Dalmano** [comment]
![Screenshot from 2019-08-05 17-15-05](https://user-images.githubusercontent.com/30301023/62479131-a444c280-b7a4-11e9-8be2-92552934e632.png)

/* Rectangle 3 */


position: absolute;
width: 80px;
height: 35.23px;
left: 194px;
top: 345px;

background: linear-gradient(90deg, rgba(242, 112, 136, 0.8) -4%, rgba(195, 54, 80, 0.8) 96.67%);
border-radius: 5px;
