### ISSUE TITLE
Server File Structure

### ISSUE THREAD

**Issue by engshorouq** [fac-graduate-programme/Nova-Foundation#67]
- server
    - controllers
        - signup
            - postUser.js
            - index.js
        - login
            - postLogin.js
            - index.js
        - poems
            - postPoem.js
            - getPoems.js
            - deletePoem.js
            - index.js
        - pictures
            - getPictures.js
            - PostPicture.js
            - deletePicture.js
            - index.js
        - logout.js
        - checkLogin.js
        - index.js
    - middlewares
    - database
        - config
            - connection.js
            - buildDummyData
            - buildDB
        - models
            - Users.js
            - Poems.js
        - queries
            - insertUser.js
            - selectUser.js
            - selectPoems.js
            - insertPoem.js
            - deletePoem.js
    - app.js
    - index.js

**Comment by IsraaSulaiman** [comment]
Since we will be using mongodb, we should have a folder entitled, models inside database. 

I dont think we need the queries related to pictures. We wont need to store them in dayabase if we used firebase storage. 

You can make another folder called storage and inside of it config file and generateURL file

**Comment by engshorouq** [comment]
I don't use MongoDB before feel free to edit this issue as you need before built it @IsraaSulaiman .

**Comment by dubhcait** [comment]
I like it as the initial file structure. Can we use firebase for authentication purposes as well?  I might be better to go with something established rather than creating it ourselves from scratch?  If it is good that is

**Comment by IsraaSulaiman** [comment]
I think there is a section about authentication in the docs but i did not dig into it. I can have a look into it tonight.
